---
title: "Un foyer qui travaille gagne plus qu’un foyer qui vit d’aides sociales "
author:
  - name: Guillaume Allègre
    email: guillaume.allegre@sciencespo.fr
    affiliation: OFCE, Sciences Po Paris
  - name: Muriel Pucci
    email: muriel.pucci@gmail.com
    affiliation: OFCE & Université Paris 1
date: "2025-12-19"    
    
categories: ["Inégalités","Protection sociale","Emploi"]
editor: visual
description: "La reprise d'emploi à plein-temps est rémunératrice par rapport aux revenus d'assistance.L’emploi paie plus que l’assistance : s’il ne permet pas toujours de sortir de la pauvreté, c’est que les travailleurs partent de trop bas."
---

La question des gains à la reprise d’emploi des allocataires des minima sociaux est régulièrement posée depuis l’instauration du RMI en 1989. D’abord temporaire, le cumul de revenus d’activité et de compléments de revenus pour travailleurs pauvres est devenu pérenne avec la prime pour l’emploi (2001) et surtout le RSA activité (2008) puis la prime d’activité (2015). Elle est à nouveau posée à l’heure actuelle avec l’annonce par Sébastien Lecornu d’un projet de loi à venir pour l’instauration d’une Allocation de solidarité unifiée (ASU). Jean-Pierre Farandou défend ce projet de loi en annonçant qu’« un foyer qui travaille doit gagner plus qu’un foyer qui ne vit que d’aides sociales ».

Dans un [document de travail OFCE](https://gallegre.github.io/GainEmploi/), nous montrons que l’emploi est toujours plus rémunérateur que l’inactivité. Les graphiques ci-dessous décrivent la variation de revenu disponible à la suite du passage de l’inactivité à un emploi à temps complet au smic pour 20 cas-types différenciés par le nombre d’enfants, la présence ou non d’un conjoint et les revenus du conjoint.

Cette analyse par cas type porte sur le revenu disponible tel qu’il est calculé par les instituts statistiques nationaux et internationaux pour mesurer le niveau de vie et estimer le taux de pauvreté monétaire. Nous faisons l’hypothèse d’un plein recours aux prestations, ce qui conduit plutôt à sous-estimer les gains à la reprise d’emploi puisque ce qui réduit ces gains, c’est la perte partielle ou totale de prestations sociales.

Cette approche ne tient compte ni du fait que travailler peut avoir un coût, en particulier dans les ménages avec enfants, ou en raison du trajet domicile-travail ; ni des aides locales sous conditions de ressources (tarification de la cantine scolaire par exemple). Symétriquement, l’approche ne tient pas compte non plus des avantages économiques liés à l’emploi, qu’ils soient immédiats (tickets restaurant, prise en charge des cartes de transport, de la mutuelle) ou différés, en termes de droits ouverts de chômage ou de retraite.

Nos cas-types décrivent une reprise d’emploi au Smic horaire. Or les travailleurs reprenant un emploi peuvent espérer un taux de salaire horaire plus élevé. En effet, plus de 95% des salariés du privé perçoivent un salaire horaire brut horaire global (y compris compléments) supérieur à 1,05 Smic ([le rapport du groupe d’experts du Smic 2025](https://www.tresor.economie.gouv.fr/Articles/284b121f-b187-4280-b327-05f18064c3fa/files/7e0b0119-7268-4fff-88f2-f624447ad391)). De plus, leur mobilité salariale est élevée : cinq ans plus tard ils gagnent 20% de plus en moyenne. En prenant en compte cette dynamique, l’intérêt monétaire à la reprise d’emploi est plus élevé que dans les cas-types que nous étudions.   

Pour reprendre les termes de Jean-Pierre Farandou, un foyer qui travaille gagne nettement plus qu’un foyer qui ne vit que d’aides sociales. Cela reste vrai pour un emploi à mi-temps même si les gains sont, bien entendu, plus faibles (de 252 à 533 euros selon les cas types). L’emploi à mi-temps réduit l’intensité de la pauvreté et permet même dans certaines configurations de dépasser le seuil de pauvreté. Le projet de loi se présente donc comme une solution à un problème qui n’existe pas. Pourtant, une loi devrait avoir pour objectif de lutter contre les problèmes réels, plutôt que contre des problèmes ressentis. Faire une loi en pointant un ressenti risque à la fois de donner l'impression que le problème est réel et de détourner l’attention des autres objectifs des politiques publiques. 

Faire en sorte que le travail paye n’est qu’un des objectifs poursuivis par les autorités publiques dans la stratégie nationale de lutte contre la pauvreté. Se focaliser seulement sur cet objectif se ferait au détriment des autres, notamment la lutte contre la pauvreté et la garantie d’un revenu décent. Dans [notre document de travail](https://gallegre.github.io/GainEmploi/), nous montrons que les revenus d’assistance assurent un niveau de vie inférieur à 40% du niveau de vie médian, soit le seuil de très grande pauvreté, dans la plupart des cas-types : personne isolée sans enfant, couple sans enfant ou avec 1 ou 2 enfants.

L’emploi paie plus que l’assistance : s’il ne permet pas toujours de sortir de la pauvreté, c’est que les travailleurs partent de trop bas.
